/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Inventario } from './inventario';
import type { Item } from './item';

export interface InventarioItem {
  id?: number;
  inventario?: Inventario;
  item?: Item;
  quantidade?: number;
}
