/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Item } from './item';

export interface LojaItem {
  id?: number;
  item?: Item;
  preco?: number;
  tipoMoeda?: string;
}
