/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Missoes } from './missoes';
import type { User } from './user';

export interface MissoesSubmissoes {
  arquivoUrl?: string;
  dataAvaliacao?: string;
  dataEnvio?: string;
  id?: number;
  missao?: Missoes;
  observacao?: string;
  status?: string;
  user?: User;
}
