/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface Missoes {
  conteudo?: string;
  descricao?: string;
  diamantesRecompensa?: number;
  esmeraldasRecompensa?: number;
  id?: number;
  moedasRecompensa?: number;
  nome?: string;
  rubysRecompensa?: number;
  xpRecompensa?: number;
}
