/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Turma } from './turma';

export interface Missoes {
  descricao?: string;
  diamantesRecompensa?: number;
  esmeraldasRecompensa?: number;
  id?: number;
  moedasRecompensa?: number;
  nome?: string;
  rubysRecompensa?: number;
  turma?: Turma;
  xpRecompensa?: number;
}
