/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface NivelDefinicao {
  id?: number;
  nome?: string;
  pontosNecessarios?: number;
}
