/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { User } from './user';

export interface Turma {
  id?: number;
  nome?: string;
  periodo?: string;
  user?: User[];
}
