/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Atributo } from './atributo';
import type { GrantedAuthority } from './grantedAuthority';
import type { UserRole } from './userRole';
import type { Turma } from './turma';

export interface User {
  accountNonExpired?: boolean;
  accountNonLocked?: boolean;
  atributo?: Atributo;
  authorities?: GrantedAuthority[];
  credentialsNonExpired?: boolean;
  email?: string;
  enabled?: boolean;
  github?: string;
  id?: number;
  nome?: string;
  password?: string;
  role?: UserRole;
  senha?: string;
  turma?: Turma;
  username?: string;
}
