/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  Atributo,
  AtributoDto,
  GetUserByIdParams,
  Instituicao,
  InstituicaoDto,
  LoginDto,
  MissaoDto,
  Missoes,
  NivelDefinicao,
  NivelDefinicaoDto,
  Token,
  Turma,
  TurmaDto,
  User,
  UserDto
} from './model';

export type createResponse200 = {
  data: Atributo
  status: 200
}
    
export type createResponseSuccess = (createResponse200) & {
  headers: Headers;
};
;

export type createResponse = (createResponseSuccess)

export const getCreateUrl = () => {


  

  return `http://localhost:3333/api/v1/atributo`
}

export const create = async (atributoDto: AtributoDto, options?: RequestInit): Promise<createResponse> => {
  
  const res = await fetch(getCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      atributoDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createResponse
}



export type getAllAtributosResponse200 = {
  data: Atributo[]
  status: 200
}
    
export type getAllAtributosResponseSuccess = (getAllAtributosResponse200) & {
  headers: Headers;
};
;

export type getAllAtributosResponse = (getAllAtributosResponseSuccess)

export const getGetAllAtributosUrl = () => {


  

  return `http://localhost:3333/api/v1/atributo/all`
}

export const getAllAtributos = async ( options?: RequestInit): Promise<getAllAtributosResponse> => {
  
  const res = await fetch(getGetAllAtributosUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getAllAtributosResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAllAtributosResponse
}



export type deleteAtributosResponse200 = {
  data: string
  status: 200
}
    
export type deleteAtributosResponseSuccess = (deleteAtributosResponse200) & {
  headers: Headers;
};
;

export type deleteAtributosResponse = (deleteAtributosResponseSuccess)

export const getDeleteAtributosUrl = (id: number,) => {


  

  return `http://localhost:3333/api/v1/atributo/${id}`
}

export const deleteAtributos = async (id: number, options?: RequestInit): Promise<deleteAtributosResponse> => {
  
  const res = await fetch(getDeleteAtributosUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteAtributosResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteAtributosResponse
}



export type getByIdAtributosResponse200 = {
  data: Atributo
  status: 200
}
    
export type getByIdAtributosResponseSuccess = (getByIdAtributosResponse200) & {
  headers: Headers;
};
;

export type getByIdAtributosResponse = (getByIdAtributosResponseSuccess)

export const getGetByIdAtributosUrl = (id: number,) => {


  

  return `http://localhost:3333/api/v1/atributo/${id}`
}

export const getByIdAtributos = async (id: number, options?: RequestInit): Promise<getByIdAtributosResponse> => {
  
  const res = await fetch(getGetByIdAtributosUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getByIdAtributosResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getByIdAtributosResponse
}



export type updateAtributosResponse200 = {
  data: Atributo
  status: 200
}
    
export type updateAtributosResponseSuccess = (updateAtributosResponse200) & {
  headers: Headers;
};
;

export type updateAtributosResponse = (updateAtributosResponseSuccess)

export const getUpdateAtributosUrl = (id: number,) => {


  

  return `http://localhost:3333/api/v1/atributo/${id}`
}

export const updateAtributos = async (id: number,
    atributoDto: AtributoDto, options?: RequestInit): Promise<updateAtributosResponse> => {
  
  const res = await fetch(getUpdateAtributosUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      atributoDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updateAtributosResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateAtributosResponse
}



export type loginResponse200 = {
  data: Token
  status: 200
}
    
export type loginResponseSuccess = (loginResponse200) & {
  headers: Headers;
};
;

export type loginResponse = (loginResponseSuccess)

export const getLoginUrl = () => {


  

  return `http://localhost:3333/api/v1/auth/login`
}

export const login = async (loginDto: LoginDto, options?: RequestInit): Promise<loginResponse> => {
  
  const res = await fetch(getLoginUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      loginDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: loginResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as loginResponse
}



export type registerResponse200 = {
  data: User
  status: 200
}
    
export type registerResponseSuccess = (registerResponse200) & {
  headers: Headers;
};
;

export type registerResponse = (registerResponseSuccess)

export const getRegisterUrl = () => {


  

  return `http://localhost:3333/api/v1/auth/register`
}

export const register = async (userDto: UserDto, options?: RequestInit): Promise<registerResponse> => {
  
  const res = await fetch(getRegisterUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      userDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: registerResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as registerResponse
}



export type resetPasswordResponse200 = {
  data: string
  status: 200
}
    
export type resetPasswordResponseSuccess = (resetPasswordResponse200) & {
  headers: Headers;
};
;

export type resetPasswordResponse = (resetPasswordResponseSuccess)

export const getResetPasswordUrl = () => {


  

  return `http://localhost:3333/api/v1/auth/reset-password`
}

export const resetPassword = async (resetPasswordBody: string, options?: RequestInit): Promise<resetPasswordResponse> => {
  
  const res = await fetch(getResetPasswordUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      resetPasswordBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: resetPasswordResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as resetPasswordResponse
}



export type createInstituicaosResponse200 = {
  data: Instituicao
  status: 200
}
    
export type createInstituicaosResponseSuccess = (createInstituicaosResponse200) & {
  headers: Headers;
};
;

export type createInstituicaosResponse = (createInstituicaosResponseSuccess)

export const getCreateInstituicaosUrl = () => {


  

  return `http://localhost:3333/api/v1/instituicao`
}

export const createInstituicaos = async (instituicaoDto: InstituicaoDto, options?: RequestInit): Promise<createInstituicaosResponse> => {
  
  const res = await fetch(getCreateInstituicaosUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      instituicaoDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createInstituicaosResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createInstituicaosResponse
}



export type getAllInstituicaosResponse200 = {
  data: Instituicao[]
  status: 200
}
    
export type getAllInstituicaosResponseSuccess = (getAllInstituicaosResponse200) & {
  headers: Headers;
};
;

export type getAllInstituicaosResponse = (getAllInstituicaosResponseSuccess)

export const getGetAllInstituicaosUrl = () => {


  

  return `http://localhost:3333/api/v1/instituicao/`
}

export const getAllInstituicaos = async ( options?: RequestInit): Promise<getAllInstituicaosResponse> => {
  
  const res = await fetch(getGetAllInstituicaosUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getAllInstituicaosResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAllInstituicaosResponse
}



export type deleteInstituicaosResponse200 = {
  data: void
  status: 200
}
    
export type deleteInstituicaosResponseSuccess = (deleteInstituicaosResponse200) & {
  headers: Headers;
};
;

export type deleteInstituicaosResponse = (deleteInstituicaosResponseSuccess)

export const getDeleteInstituicaosUrl = (id: number,) => {


  

  return `http://localhost:3333/api/v1/instituicao/${id}`
}

export const deleteInstituicaos = async (id: number, options?: RequestInit): Promise<deleteInstituicaosResponse> => {
  
  const res = await fetch(getDeleteInstituicaosUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteInstituicaosResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteInstituicaosResponse
}



export type getByIdInstituicaosResponse200 = {
  data: Instituicao
  status: 200
}
    
export type getByIdInstituicaosResponseSuccess = (getByIdInstituicaosResponse200) & {
  headers: Headers;
};
;

export type getByIdInstituicaosResponse = (getByIdInstituicaosResponseSuccess)

export const getGetByIdInstituicaosUrl = (id: number,) => {


  

  return `http://localhost:3333/api/v1/instituicao/${id}`
}

export const getByIdInstituicaos = async (id: number, options?: RequestInit): Promise<getByIdInstituicaosResponse> => {
  
  const res = await fetch(getGetByIdInstituicaosUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getByIdInstituicaosResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getByIdInstituicaosResponse
}



export type updateInstituicaosResponse200 = {
  data: Instituicao
  status: 200
}
    
export type updateInstituicaosResponseSuccess = (updateInstituicaosResponse200) & {
  headers: Headers;
};
;

export type updateInstituicaosResponse = (updateInstituicaosResponseSuccess)

export const getUpdateInstituicaosUrl = (id: number,) => {


  

  return `http://localhost:3333/api/v1/instituicao/${id}`
}

export const updateInstituicaos = async (id: number,
    instituicaoDto: InstituicaoDto, options?: RequestInit): Promise<updateInstituicaosResponse> => {
  
  const res = await fetch(getUpdateInstituicaosUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      instituicaoDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updateInstituicaosResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateInstituicaosResponse
}



export type findAlMissoesResponse200 = {
  data: Missoes[]
  status: 200
}
    
export type findAlMissoesResponseSuccess = (findAlMissoesResponse200) & {
  headers: Headers;
};
;

export type findAlMissoesResponse = (findAlMissoesResponseSuccess)

export const getFindAlMissoesUrl = () => {


  

  return `http://localhost:3333/api/v1/missions`
}

export const findAlMissoes = async ( options?: RequestInit): Promise<findAlMissoesResponse> => {
  
  const res = await fetch(getFindAlMissoesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: findAlMissoesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as findAlMissoesResponse
}



export type createMissoesResponse200 = {
  data: Missoes
  status: 200
}
    
export type createMissoesResponseSuccess = (createMissoesResponse200) & {
  headers: Headers;
};
;

export type createMissoesResponse = (createMissoesResponseSuccess)

export const getCreateMissoesUrl = () => {


  

  return `http://localhost:3333/api/v1/missions`
}

export const createMissoes = async (missaoDto: MissaoDto, options?: RequestInit): Promise<createMissoesResponse> => {
  
  const res = await fetch(getCreateMissoesUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      missaoDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createMissoesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createMissoesResponse
}



export type deleteMissoesResponse200 = {
  data: string
  status: 200
}
    
export type deleteMissoesResponseSuccess = (deleteMissoesResponse200) & {
  headers: Headers;
};
;

export type deleteMissoesResponse = (deleteMissoesResponseSuccess)

export const getDeleteMissoesUrl = (id: number,) => {


  

  return `http://localhost:3333/api/v1/missions/${id}`
}

export const deleteMissoes = async (id: number, options?: RequestInit): Promise<deleteMissoesResponse> => {
  
  const res = await fetch(getDeleteMissoesUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteMissoesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteMissoesResponse
}



export type createNivelDefinicaoResponse200 = {
  data: NivelDefinicao
  status: 200
}
    
export type createNivelDefinicaoResponseSuccess = (createNivelDefinicaoResponse200) & {
  headers: Headers;
};
;

export type createNivelDefinicaoResponse = (createNivelDefinicaoResponseSuccess)

export const getCreateNivelDefinicaoUrl = () => {


  

  return `http://localhost:3333/api/v1/nivel-definicao`
}

export const createNivelDefinicao = async (nivelDefinicaoDto: NivelDefinicaoDto, options?: RequestInit): Promise<createNivelDefinicaoResponse> => {
  
  const res = await fetch(getCreateNivelDefinicaoUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      nivelDefinicaoDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createNivelDefinicaoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createNivelDefinicaoResponse
}



export type getAllNivelDefinicaoResponse200 = {
  data: NivelDefinicao[]
  status: 200
}
    
export type getAllNivelDefinicaoResponseSuccess = (getAllNivelDefinicaoResponse200) & {
  headers: Headers;
};
;

export type getAllNivelDefinicaoResponse = (getAllNivelDefinicaoResponseSuccess)

export const getGetAllNivelDefinicaoUrl = () => {


  

  return `http://localhost:3333/api/v1/nivel-definicao/all`
}

export const getAllNivelDefinicao = async ( options?: RequestInit): Promise<getAllNivelDefinicaoResponse> => {
  
  const res = await fetch(getGetAllNivelDefinicaoUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getAllNivelDefinicaoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAllNivelDefinicaoResponse
}



export type deleteNivelDefinicaoResponse200 = {
  data: string
  status: 200
}
    
export type deleteNivelDefinicaoResponseSuccess = (deleteNivelDefinicaoResponse200) & {
  headers: Headers;
};
;

export type deleteNivelDefinicaoResponse = (deleteNivelDefinicaoResponseSuccess)

export const getDeleteNivelDefinicaoUrl = (id: number,) => {


  

  return `http://localhost:3333/api/v1/nivel-definicao/${id}`
}

export const deleteNivelDefinicao = async (id: number, options?: RequestInit): Promise<deleteNivelDefinicaoResponse> => {
  
  const res = await fetch(getDeleteNivelDefinicaoUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteNivelDefinicaoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteNivelDefinicaoResponse
}



export type getByIdNivelDefinicaoResponse200 = {
  data: NivelDefinicao
  status: 200
}
    
export type getByIdNivelDefinicaoResponseSuccess = (getByIdNivelDefinicaoResponse200) & {
  headers: Headers;
};
;

export type getByIdNivelDefinicaoResponse = (getByIdNivelDefinicaoResponseSuccess)

export const getGetByIdNivelDefinicaoUrl = (id: number,) => {


  

  return `http://localhost:3333/api/v1/nivel-definicao/${id}`
}

export const getByIdNivelDefinicao = async (id: number, options?: RequestInit): Promise<getByIdNivelDefinicaoResponse> => {
  
  const res = await fetch(getGetByIdNivelDefinicaoUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getByIdNivelDefinicaoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getByIdNivelDefinicaoResponse
}



export type updateNivelDefinicaoResponse200 = {
  data: NivelDefinicao
  status: 200
}
    
export type updateNivelDefinicaoResponseSuccess = (updateNivelDefinicaoResponse200) & {
  headers: Headers;
};
;

export type updateNivelDefinicaoResponse = (updateNivelDefinicaoResponseSuccess)

export const getUpdateNivelDefinicaoUrl = (id: number,) => {


  

  return `http://localhost:3333/api/v1/nivel-definicao/${id}`
}

export const updateNivelDefinicao = async (id: number,
    nivelDefinicaoDto: NivelDefinicaoDto, options?: RequestInit): Promise<updateNivelDefinicaoResponse> => {
  
  const res = await fetch(getUpdateNivelDefinicaoUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      nivelDefinicaoDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updateNivelDefinicaoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateNivelDefinicaoResponse
}



export type createTurmaResponse200 = {
  data: Turma
  status: 200
}
    
export type createTurmaResponseSuccess = (createTurmaResponse200) & {
  headers: Headers;
};
;

export type createTurmaResponse = (createTurmaResponseSuccess)

export const getCreateTurmaUrl = () => {


  

  return `http://localhost:3333/api/v1/turma`
}

export const createTurma = async (turmaDto: TurmaDto, options?: RequestInit): Promise<createTurmaResponse> => {
  
  const res = await fetch(getCreateTurmaUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      turmaDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createTurmaResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createTurmaResponse
}



export type getAllTurmaResponse200 = {
  data: Turma[]
  status: 200
}
    
export type getAllTurmaResponseSuccess = (getAllTurmaResponse200) & {
  headers: Headers;
};
;

export type getAllTurmaResponse = (getAllTurmaResponseSuccess)

export const getGetAllTurmaUrl = () => {


  

  return `http://localhost:3333/api/v1/turma/all`
}

export const getAllTurma = async ( options?: RequestInit): Promise<getAllTurmaResponse> => {
  
  const res = await fetch(getGetAllTurmaUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getAllTurmaResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAllTurmaResponse
}



export type getTurmasResponse200 = {
  data: number
  status: 200
}
    
export type getTurmasResponseSuccess = (getTurmasResponse200) & {
  headers: Headers;
};
;

export type getTurmasResponse = (getTurmasResponseSuccess)

export const getGetTurmasUrl = () => {


  

  return `http://localhost:3333/api/v1/turma/qt`
}

export const getTurmas = async ( options?: RequestInit): Promise<getTurmasResponse> => {
  
  const res = await fetch(getGetTurmasUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getTurmasResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getTurmasResponse
}



export type deleteTurmaResponse200 = {
  data: string
  status: 200
}
    
export type deleteTurmaResponseSuccess = (deleteTurmaResponse200) & {
  headers: Headers;
};
;

export type deleteTurmaResponse = (deleteTurmaResponseSuccess)

export const getDeleteTurmaUrl = (id: number,) => {


  

  return `http://localhost:3333/api/v1/turma/${id}`
}

export const deleteTurma = async (id: number, options?: RequestInit): Promise<deleteTurmaResponse> => {
  
  const res = await fetch(getDeleteTurmaUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteTurmaResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteTurmaResponse
}



export type updateTurmaResponse200 = {
  data: Turma
  status: 200
}
    
export type updateTurmaResponseSuccess = (updateTurmaResponse200) & {
  headers: Headers;
};
;

export type updateTurmaResponse = (updateTurmaResponseSuccess)

export const getUpdateTurmaUrl = (id: number,) => {


  

  return `http://localhost:3333/api/v1/turma/${id}`
}

export const updateTurma = async (id: number,
    turmaDto: TurmaDto, options?: RequestInit): Promise<updateTurmaResponse> => {
  
  const res = await fetch(getUpdateTurmaUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      turmaDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updateTurmaResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateTurmaResponse
}



export type getUserByIdResponse200 = {
  data: User
  status: 200
}
    
export type getUserByIdResponseSuccess = (getUserByIdResponse200) & {
  headers: Headers;
};
;

export type getUserByIdResponse = (getUserByIdResponseSuccess)

export const getGetUserByIdUrl = (params: GetUserByIdParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:3333/api/v1/user?${stringifiedParams}` : `http://localhost:3333/api/v1/user`
}

export const getUserById = async (params: GetUserByIdParams, options?: RequestInit): Promise<getUserByIdResponse> => {
  
  const res = await fetch(getGetUserByIdUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getUserByIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getUserByIdResponse
}



export type createUserResponse200 = {
  data: User
  status: 200
}
    
export type createUserResponseSuccess = (createUserResponse200) & {
  headers: Headers;
};
;

export type createUserResponse = (createUserResponseSuccess)

export const getCreateUserUrl = () => {


  

  return `http://localhost:3333/api/v1/user`
}

export const createUser = async (userDto: UserDto, options?: RequestInit): Promise<createUserResponse> => {
  
  const res = await fetch(getCreateUserUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      userDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createUserResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createUserResponse
}



export type getUserResponse200 = {
  data: User[]
  status: 200
}
    
export type getUserResponseSuccess = (getUserResponse200) & {
  headers: Headers;
};
;

export type getUserResponse = (getUserResponseSuccess)

export const getGetUserUrl = () => {


  

  return `http://localhost:3333/api/v1/user/all`
}

export const getUser = async ( options?: RequestInit): Promise<getUserResponse> => {
  
  const res = await fetch(getGetUserUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getUserResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getUserResponse
}



export type getQtUsersResponse200 = {
  data: number
  status: 200
}
    
export type getQtUsersResponseSuccess = (getQtUsersResponse200) & {
  headers: Headers;
};
;

export type getQtUsersResponse = (getQtUsersResponseSuccess)

export const getGetQtUsersUrl = () => {


  

  return `http://localhost:3333/api/v1/user/qt`
}

export const getQtUsers = async ( options?: RequestInit): Promise<getQtUsersResponse> => {
  
  const res = await fetch(getGetQtUsersUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getQtUsersResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getQtUsersResponse
}
