/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  Atributo,
  AtributoDto,
  GetAllQuestionarios200,
  GetUserByIdParams,
  Instituicao,
  InstituicaoDto,
  InventarioItem,
  Item,
  ItemDto,
  LoginDto,
  LojaItem,
  MissaoDto,
  Missoes,
  MissoesSubmissoes,
  NivelDefinicao,
  NivelDefinicaoDto,
  Questionario,
  Token,
  Turma,
  TurmaDto,
  User,
  UserDto
} from './model';

export type createResponse200 = {
  data: Atributo
  status: 200
}
    
export type createResponseSuccess = (createResponse200) & {
  headers: Headers;
};
;

export type createResponse = (createResponseSuccess)

export const getCreateUrl = () => {


  

  return `http://localhost:3333/api/v1/atributo`
}

export const create = async (atributoDto: AtributoDto, options?: RequestInit): Promise<createResponse> => {
  
  const res = await fetch(getCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      atributoDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createResponse
}



export type getAllAtributosResponse200 = {
  data: Atributo[]
  status: 200
}
    
export type getAllAtributosResponseSuccess = (getAllAtributosResponse200) & {
  headers: Headers;
};
;

export type getAllAtributosResponse = (getAllAtributosResponseSuccess)

export const getGetAllAtributosUrl = () => {


  

  return `http://localhost:3333/api/v1/atributo/all`
}

export const getAllAtributos = async ( options?: RequestInit): Promise<getAllAtributosResponse> => {
  
  const res = await fetch(getGetAllAtributosUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getAllAtributosResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAllAtributosResponse
}



export type deleteAtributosResponse200 = {
  data: string
  status: 200
}
    
export type deleteAtributosResponseSuccess = (deleteAtributosResponse200) & {
  headers: Headers;
};
;

export type deleteAtributosResponse = (deleteAtributosResponseSuccess)

export const getDeleteAtributosUrl = (id: number,) => {


  

  return `http://localhost:3333/api/v1/atributo/${id}`
}

export const deleteAtributos = async (id: number, options?: RequestInit): Promise<deleteAtributosResponse> => {
  
  const res = await fetch(getDeleteAtributosUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteAtributosResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteAtributosResponse
}



export type getByIdAtributosResponse200 = {
  data: Atributo
  status: 200
}
    
export type getByIdAtributosResponseSuccess = (getByIdAtributosResponse200) & {
  headers: Headers;
};
;

export type getByIdAtributosResponse = (getByIdAtributosResponseSuccess)

export const getGetByIdAtributosUrl = (id: number,) => {


  

  return `http://localhost:3333/api/v1/atributo/${id}`
}

export const getByIdAtributos = async (id: number, options?: RequestInit): Promise<getByIdAtributosResponse> => {
  
  const res = await fetch(getGetByIdAtributosUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getByIdAtributosResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getByIdAtributosResponse
}



export type updateAtributosResponse200 = {
  data: Atributo
  status: 200
}
    
export type updateAtributosResponseSuccess = (updateAtributosResponse200) & {
  headers: Headers;
};
;

export type updateAtributosResponse = (updateAtributosResponseSuccess)

export const getUpdateAtributosUrl = (id: number,) => {


  

  return `http://localhost:3333/api/v1/atributo/${id}`
}

export const updateAtributos = async (id: number,
    atributoDto: AtributoDto, options?: RequestInit): Promise<updateAtributosResponse> => {
  
  const res = await fetch(getUpdateAtributosUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      atributoDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updateAtributosResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateAtributosResponse
}



export type loginResponse200 = {
  data: Token
  status: 200
}
    
export type loginResponseSuccess = (loginResponse200) & {
  headers: Headers;
};
;

export type loginResponse = (loginResponseSuccess)

export const getLoginUrl = () => {


  

  return `http://localhost:3333/api/v1/auth/login`
}

export const login = async (loginDto: LoginDto, options?: RequestInit): Promise<loginResponse> => {
  
  const res = await fetch(getLoginUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      loginDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: loginResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as loginResponse
}



export type registerResponse200 = {
  data: User
  status: 200
}
    
export type registerResponseSuccess = (registerResponse200) & {
  headers: Headers;
};
;

export type registerResponse = (registerResponseSuccess)

export const getRegisterUrl = () => {


  

  return `http://localhost:3333/api/v1/auth/register`
}

export const register = async (userDto: UserDto, options?: RequestInit): Promise<registerResponse> => {
  
  const res = await fetch(getRegisterUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      userDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: registerResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as registerResponse
}



export type resetPasswordResponse200 = {
  data: string
  status: 200
}
    
export type resetPasswordResponseSuccess = (resetPasswordResponse200) & {
  headers: Headers;
};
;

export type resetPasswordResponse = (resetPasswordResponseSuccess)

export const getResetPasswordUrl = () => {


  

  return `http://localhost:3333/api/v1/auth/reset-password`
}

export const resetPassword = async (resetPasswordBody: string, options?: RequestInit): Promise<resetPasswordResponse> => {
  
  const res = await fetch(getResetPasswordUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      resetPasswordBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: resetPasswordResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as resetPasswordResponse
}



export type createInstituicaosResponse200 = {
  data: Instituicao
  status: 200
}
    
export type createInstituicaosResponseSuccess = (createInstituicaosResponse200) & {
  headers: Headers;
};
;

export type createInstituicaosResponse = (createInstituicaosResponseSuccess)

export const getCreateInstituicaosUrl = () => {


  

  return `http://localhost:3333/api/v1/instituicao`
}

export const createInstituicaos = async (instituicaoDto: InstituicaoDto, options?: RequestInit): Promise<createInstituicaosResponse> => {
  
  const res = await fetch(getCreateInstituicaosUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      instituicaoDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createInstituicaosResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createInstituicaosResponse
}



export type getAllInstituicaosResponse200 = {
  data: Instituicao[]
  status: 200
}
    
export type getAllInstituicaosResponseSuccess = (getAllInstituicaosResponse200) & {
  headers: Headers;
};
;

export type getAllInstituicaosResponse = (getAllInstituicaosResponseSuccess)

export const getGetAllInstituicaosUrl = () => {


  

  return `http://localhost:3333/api/v1/instituicao/`
}

export const getAllInstituicaos = async ( options?: RequestInit): Promise<getAllInstituicaosResponse> => {
  
  const res = await fetch(getGetAllInstituicaosUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getAllInstituicaosResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAllInstituicaosResponse
}



export type deleteInstituicaosResponse200 = {
  data: void
  status: 200
}
    
export type deleteInstituicaosResponseSuccess = (deleteInstituicaosResponse200) & {
  headers: Headers;
};
;

export type deleteInstituicaosResponse = (deleteInstituicaosResponseSuccess)

export const getDeleteInstituicaosUrl = (id: number,) => {


  

  return `http://localhost:3333/api/v1/instituicao/${id}`
}

export const deleteInstituicaos = async (id: number, options?: RequestInit): Promise<deleteInstituicaosResponse> => {
  
  const res = await fetch(getDeleteInstituicaosUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteInstituicaosResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteInstituicaosResponse
}



export type getByIdInstituicaosResponse200 = {
  data: Instituicao
  status: 200
}
    
export type getByIdInstituicaosResponseSuccess = (getByIdInstituicaosResponse200) & {
  headers: Headers;
};
;

export type getByIdInstituicaosResponse = (getByIdInstituicaosResponseSuccess)

export const getGetByIdInstituicaosUrl = (id: number,) => {


  

  return `http://localhost:3333/api/v1/instituicao/${id}`
}

export const getByIdInstituicaos = async (id: number, options?: RequestInit): Promise<getByIdInstituicaosResponse> => {
  
  const res = await fetch(getGetByIdInstituicaosUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getByIdInstituicaosResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getByIdInstituicaosResponse
}



export type updateInstituicaosResponse200 = {
  data: Instituicao
  status: 200
}
    
export type updateInstituicaosResponseSuccess = (updateInstituicaosResponse200) & {
  headers: Headers;
};
;

export type updateInstituicaosResponse = (updateInstituicaosResponseSuccess)

export const getUpdateInstituicaosUrl = (id: number,) => {


  

  return `http://localhost:3333/api/v1/instituicao/${id}`
}

export const updateInstituicaos = async (id: number,
    instituicaoDto: InstituicaoDto, options?: RequestInit): Promise<updateInstituicaosResponse> => {
  
  const res = await fetch(getUpdateInstituicaosUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      instituicaoDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updateInstituicaosResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateInstituicaosResponse
}



export type createInventarioItemResponse200 = {
  data: InventarioItem
  status: 200
}
    
export type createInventarioItemResponseSuccess = (createInventarioItemResponse200) & {
  headers: Headers;
};
;

export type createInventarioItemResponse = (createInventarioItemResponseSuccess)

export const getCreateInventarioItemUrl = () => {


  

  return `http://localhost:3333/api/v1/inventario-item`
}

export const createInventarioItem = async (inventarioItem: InventarioItem, options?: RequestInit): Promise<createInventarioItemResponse> => {
  
  const res = await fetch(getCreateInventarioItemUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      inventarioItem,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createInventarioItemResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createInventarioItemResponse
}



export type getAllInventarioItemsResponse200 = {
  data: InventarioItem[]
  status: 200
}
    
export type getAllInventarioItemsResponseSuccess = (getAllInventarioItemsResponse200) & {
  headers: Headers;
};
;

export type getAllInventarioItemsResponse = (getAllInventarioItemsResponseSuccess)

export const getGetAllInventarioItemsUrl = () => {


  

  return `http://localhost:3333/api/v1/inventario-item/all`
}

export const getAllInventarioItems = async ( options?: RequestInit): Promise<getAllInventarioItemsResponse> => {
  
  const res = await fetch(getGetAllInventarioItemsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getAllInventarioItemsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAllInventarioItemsResponse
}



export type getInventarioItemsByUserResponse200 = {
  data: InventarioItem[]
  status: 200
}
    
export type getInventarioItemsByUserResponseSuccess = (getInventarioItemsByUserResponse200) & {
  headers: Headers;
};
;

export type getInventarioItemsByUserResponse = (getInventarioItemsByUserResponseSuccess)

export const getGetInventarioItemsByUserUrl = (userId: number,) => {


  

  return `http://localhost:3333/api/v1/inventario-item/user/${userId}`
}

export const getInventarioItemsByUser = async (userId: number, options?: RequestInit): Promise<getInventarioItemsByUserResponse> => {
  
  const res = await fetch(getGetInventarioItemsByUserUrl(userId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getInventarioItemsByUserResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getInventarioItemsByUserResponse
}



export type deleteInventarioItemResponse200 = {
  data: string
  status: 200
}
    
export type deleteInventarioItemResponseSuccess = (deleteInventarioItemResponse200) & {
  headers: Headers;
};
;

export type deleteInventarioItemResponse = (deleteInventarioItemResponseSuccess)

export const getDeleteInventarioItemUrl = (id: number,) => {


  

  return `http://localhost:3333/api/v1/inventario-item/${id}`
}

export const deleteInventarioItem = async (id: number, options?: RequestInit): Promise<deleteInventarioItemResponse> => {
  
  const res = await fetch(getDeleteInventarioItemUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteInventarioItemResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteInventarioItemResponse
}



export type getByIdInventarioItemResponse200 = {
  data: InventarioItem
  status: 200
}
    
export type getByIdInventarioItemResponseSuccess = (getByIdInventarioItemResponse200) & {
  headers: Headers;
};
;

export type getByIdInventarioItemResponse = (getByIdInventarioItemResponseSuccess)

export const getGetByIdInventarioItemUrl = (id: number,) => {


  

  return `http://localhost:3333/api/v1/inventario-item/${id}`
}

export const getByIdInventarioItem = async (id: number, options?: RequestInit): Promise<getByIdInventarioItemResponse> => {
  
  const res = await fetch(getGetByIdInventarioItemUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getByIdInventarioItemResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getByIdInventarioItemResponse
}



export type updateInventarioItemResponse200 = {
  data: InventarioItem
  status: 200
}
    
export type updateInventarioItemResponseSuccess = (updateInventarioItemResponse200) & {
  headers: Headers;
};
;

export type updateInventarioItemResponse = (updateInventarioItemResponseSuccess)

export const getUpdateInventarioItemUrl = (id: number,) => {


  

  return `http://localhost:3333/api/v1/inventario-item/${id}`
}

export const updateInventarioItem = async (id: number,
    inventarioItem: InventarioItem, options?: RequestInit): Promise<updateInventarioItemResponse> => {
  
  const res = await fetch(getUpdateInventarioItemUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      inventarioItem,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updateInventarioItemResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateInventarioItemResponse
}



export type createItemResponse200 = {
  data: Item
  status: 200
}
    
export type createItemResponseSuccess = (createItemResponse200) & {
  headers: Headers;
};
;

export type createItemResponse = (createItemResponseSuccess)

export const getCreateItemUrl = () => {


  

  return `http://localhost:3333/api/v1/item`
}

export const createItem = async (itemDto: ItemDto, options?: RequestInit): Promise<createItemResponse> => {
  
  const res = await fetch(getCreateItemUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      itemDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createItemResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createItemResponse
}



export type getAllItemsResponse200 = {
  data: Item[]
  status: 200
}
    
export type getAllItemsResponseSuccess = (getAllItemsResponse200) & {
  headers: Headers;
};
;

export type getAllItemsResponse = (getAllItemsResponseSuccess)

export const getGetAllItemsUrl = () => {


  

  return `http://localhost:3333/api/v1/item/all`
}

export const getAllItems = async ( options?: RequestInit): Promise<getAllItemsResponse> => {
  
  const res = await fetch(getGetAllItemsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getAllItemsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAllItemsResponse
}



export type deleteItemResponse200 = {
  data: string
  status: 200
}
    
export type deleteItemResponseSuccess = (deleteItemResponse200) & {
  headers: Headers;
};
;

export type deleteItemResponse = (deleteItemResponseSuccess)

export const getDeleteItemUrl = (id: number,) => {


  

  return `http://localhost:3333/api/v1/item/${id}`
}

export const deleteItem = async (id: number, options?: RequestInit): Promise<deleteItemResponse> => {
  
  const res = await fetch(getDeleteItemUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteItemResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteItemResponse
}



export type getByIdItemResponse200 = {
  data: Item
  status: 200
}
    
export type getByIdItemResponseSuccess = (getByIdItemResponse200) & {
  headers: Headers;
};
;

export type getByIdItemResponse = (getByIdItemResponseSuccess)

export const getGetByIdItemUrl = (id: number,) => {


  

  return `http://localhost:3333/api/v1/item/${id}`
}

export const getByIdItem = async (id: number, options?: RequestInit): Promise<getByIdItemResponse> => {
  
  const res = await fetch(getGetByIdItemUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getByIdItemResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getByIdItemResponse
}



export type updateItemResponse200 = {
  data: Item
  status: 200
}
    
export type updateItemResponseSuccess = (updateItemResponse200) & {
  headers: Headers;
};
;

export type updateItemResponse = (updateItemResponseSuccess)

export const getUpdateItemUrl = (id: number,) => {


  

  return `http://localhost:3333/api/v1/item/${id}`
}

export const updateItem = async (id: number,
    itemDto: ItemDto, options?: RequestInit): Promise<updateItemResponse> => {
  
  const res = await fetch(getUpdateItemUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      itemDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updateItemResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateItemResponse
}



export type createLojaItemResponse200 = {
  data: LojaItem
  status: 200
}
    
export type createLojaItemResponseSuccess = (createLojaItemResponse200) & {
  headers: Headers;
};
;

export type createLojaItemResponse = (createLojaItemResponseSuccess)

export const getCreateLojaItemUrl = () => {


  

  return `http://localhost:3333/api/v1/loja-item`
}

export const createLojaItem = async (lojaItem: LojaItem, options?: RequestInit): Promise<createLojaItemResponse> => {
  
  const res = await fetch(getCreateLojaItemUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      lojaItem,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createLojaItemResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createLojaItemResponse
}



export type getAllLojaItemsResponse200 = {
  data: LojaItem[]
  status: 200
}
    
export type getAllLojaItemsResponseSuccess = (getAllLojaItemsResponse200) & {
  headers: Headers;
};
;

export type getAllLojaItemsResponse = (getAllLojaItemsResponseSuccess)

export const getGetAllLojaItemsUrl = () => {


  

  return `http://localhost:3333/api/v1/loja-item/all`
}

export const getAllLojaItems = async ( options?: RequestInit): Promise<getAllLojaItemsResponse> => {
  
  const res = await fetch(getGetAllLojaItemsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getAllLojaItemsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAllLojaItemsResponse
}



export type deleteLojaItemResponse200 = {
  data: string
  status: 200
}
    
export type deleteLojaItemResponseSuccess = (deleteLojaItemResponse200) & {
  headers: Headers;
};
;

export type deleteLojaItemResponse = (deleteLojaItemResponseSuccess)

export const getDeleteLojaItemUrl = (id: number,) => {


  

  return `http://localhost:3333/api/v1/loja-item/${id}`
}

export const deleteLojaItem = async (id: number, options?: RequestInit): Promise<deleteLojaItemResponse> => {
  
  const res = await fetch(getDeleteLojaItemUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteLojaItemResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteLojaItemResponse
}



export type getByIdLojaItemResponse200 = {
  data: LojaItem
  status: 200
}
    
export type getByIdLojaItemResponseSuccess = (getByIdLojaItemResponse200) & {
  headers: Headers;
};
;

export type getByIdLojaItemResponse = (getByIdLojaItemResponseSuccess)

export const getGetByIdLojaItemUrl = (id: number,) => {


  

  return `http://localhost:3333/api/v1/loja-item/${id}`
}

export const getByIdLojaItem = async (id: number, options?: RequestInit): Promise<getByIdLojaItemResponse> => {
  
  const res = await fetch(getGetByIdLojaItemUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getByIdLojaItemResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getByIdLojaItemResponse
}



export type updateLojaItemResponse200 = {
  data: LojaItem
  status: 200
}
    
export type updateLojaItemResponseSuccess = (updateLojaItemResponse200) & {
  headers: Headers;
};
;

export type updateLojaItemResponse = (updateLojaItemResponseSuccess)

export const getUpdateLojaItemUrl = (id: number,) => {


  

  return `http://localhost:3333/api/v1/loja-item/${id}`
}

export const updateLojaItem = async (id: number,
    lojaItem: LojaItem, options?: RequestInit): Promise<updateLojaItemResponse> => {
  
  const res = await fetch(getUpdateLojaItemUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      lojaItem,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updateLojaItemResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateLojaItemResponse
}



export type getAllMissoesResponse200 = {
  data: Missoes[]
  status: 200
}
    
export type getAllMissoesResponseSuccess = (getAllMissoesResponse200) & {
  headers: Headers;
};
;

export type getAllMissoesResponse = (getAllMissoesResponseSuccess)

export const getGetAllMissoesUrl = () => {


  

  return `http://localhost:3333/api/v1/missions`
}

export const getAllMissoes = async ( options?: RequestInit): Promise<getAllMissoesResponse> => {
  
  const res = await fetch(getGetAllMissoesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getAllMissoesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAllMissoesResponse
}



export type createMissoesResponse200 = {
  data: Missoes
  status: 200
}
    
export type createMissoesResponseSuccess = (createMissoesResponse200) & {
  headers: Headers;
};
;

export type createMissoesResponse = (createMissoesResponseSuccess)

export const getCreateMissoesUrl = () => {


  

  return `http://localhost:3333/api/v1/missions`
}

export const createMissoes = async (missaoDto: MissaoDto, options?: RequestInit): Promise<createMissoesResponse> => {
  
  const res = await fetch(getCreateMissoesUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      missaoDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createMissoesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createMissoesResponse
}



export type deleteMissoesResponse200 = {
  data: string
  status: 200
}
    
export type deleteMissoesResponseSuccess = (deleteMissoesResponse200) & {
  headers: Headers;
};
;

export type deleteMissoesResponse = (deleteMissoesResponseSuccess)

export const getDeleteMissoesUrl = (id: number,) => {


  

  return `http://localhost:3333/api/v1/missions/${id}`
}

export const deleteMissoes = async (id: number, options?: RequestInit): Promise<deleteMissoesResponse> => {
  
  const res = await fetch(getDeleteMissoesUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteMissoesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteMissoesResponse
}



export type createSubmissaoResponse200 = {
  data: MissoesSubmissoes
  status: 200
}
    
export type createSubmissaoResponseSuccess = (createSubmissaoResponse200) & {
  headers: Headers;
};
;

export type createSubmissaoResponse = (createSubmissaoResponseSuccess)

export const getCreateSubmissaoUrl = () => {


  

  return `http://localhost:3333/api/v1/missoes-submissoes`
}

export const createSubmissao = async (missoesSubmissoes: MissoesSubmissoes, options?: RequestInit): Promise<createSubmissaoResponse> => {
  
  const res = await fetch(getCreateSubmissaoUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      missoesSubmissoes,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createSubmissaoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createSubmissaoResponse
}



export type getAllSubmissoesResponse200 = {
  data: MissoesSubmissoes[]
  status: 200
}
    
export type getAllSubmissoesResponseSuccess = (getAllSubmissoesResponse200) & {
  headers: Headers;
};
;

export type getAllSubmissoesResponse = (getAllSubmissoesResponseSuccess)

export const getGetAllSubmissoesUrl = () => {


  

  return `http://localhost:3333/api/v1/missoes-submissoes/all`
}

export const getAllSubmissoes = async ( options?: RequestInit): Promise<getAllSubmissoesResponse> => {
  
  const res = await fetch(getGetAllSubmissoesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getAllSubmissoesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAllSubmissoesResponse
}



export type getSubmissoesByUserResponse200 = {
  data: MissoesSubmissoes[]
  status: 200
}
    
export type getSubmissoesByUserResponseSuccess = (getSubmissoesByUserResponse200) & {
  headers: Headers;
};
;

export type getSubmissoesByUserResponse = (getSubmissoesByUserResponseSuccess)

export const getGetSubmissoesByUserUrl = (userId: number,) => {


  

  return `http://localhost:3333/api/v1/missoes-submissoes/user/${userId}`
}

export const getSubmissoesByUser = async (userId: number, options?: RequestInit): Promise<getSubmissoesByUserResponse> => {
  
  const res = await fetch(getGetSubmissoesByUserUrl(userId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getSubmissoesByUserResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getSubmissoesByUserResponse
}



export type deleteSubmissaoResponse200 = {
  data: string
  status: 200
}
    
export type deleteSubmissaoResponseSuccess = (deleteSubmissaoResponse200) & {
  headers: Headers;
};
;

export type deleteSubmissaoResponse = (deleteSubmissaoResponseSuccess)

export const getDeleteSubmissaoUrl = (id: number,) => {


  

  return `http://localhost:3333/api/v1/missoes-submissoes/${id}`
}

export const deleteSubmissao = async (id: number, options?: RequestInit): Promise<deleteSubmissaoResponse> => {
  
  const res = await fetch(getDeleteSubmissaoUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteSubmissaoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteSubmissaoResponse
}



export type updateSubmissaoResponse200 = {
  data: MissoesSubmissoes
  status: 200
}
    
export type updateSubmissaoResponseSuccess = (updateSubmissaoResponse200) & {
  headers: Headers;
};
;

export type updateSubmissaoResponse = (updateSubmissaoResponseSuccess)

export const getUpdateSubmissaoUrl = (id: number,) => {


  

  return `http://localhost:3333/api/v1/missoes-submissoes/${id}`
}

export const updateSubmissao = async (id: number,
    missoesSubmissoes: MissoesSubmissoes, options?: RequestInit): Promise<updateSubmissaoResponse> => {
  
  const res = await fetch(getUpdateSubmissaoUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      missoesSubmissoes,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updateSubmissaoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateSubmissaoResponse
}



export type createNivelDefinicaoResponse200 = {
  data: NivelDefinicao
  status: 200
}
    
export type createNivelDefinicaoResponseSuccess = (createNivelDefinicaoResponse200) & {
  headers: Headers;
};
;

export type createNivelDefinicaoResponse = (createNivelDefinicaoResponseSuccess)

export const getCreateNivelDefinicaoUrl = () => {


  

  return `http://localhost:3333/api/v1/nivel-definicao`
}

export const createNivelDefinicao = async (nivelDefinicaoDto: NivelDefinicaoDto, options?: RequestInit): Promise<createNivelDefinicaoResponse> => {
  
  const res = await fetch(getCreateNivelDefinicaoUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      nivelDefinicaoDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createNivelDefinicaoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createNivelDefinicaoResponse
}



export type getAllNivelDefinicaoResponse200 = {
  data: NivelDefinicao[]
  status: 200
}
    
export type getAllNivelDefinicaoResponseSuccess = (getAllNivelDefinicaoResponse200) & {
  headers: Headers;
};
;

export type getAllNivelDefinicaoResponse = (getAllNivelDefinicaoResponseSuccess)

export const getGetAllNivelDefinicaoUrl = () => {


  

  return `http://localhost:3333/api/v1/nivel-definicao/all`
}

export const getAllNivelDefinicao = async ( options?: RequestInit): Promise<getAllNivelDefinicaoResponse> => {
  
  const res = await fetch(getGetAllNivelDefinicaoUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getAllNivelDefinicaoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAllNivelDefinicaoResponse
}



export type deleteNivelDefinicaoResponse200 = {
  data: string
  status: 200
}
    
export type deleteNivelDefinicaoResponseSuccess = (deleteNivelDefinicaoResponse200) & {
  headers: Headers;
};
;

export type deleteNivelDefinicaoResponse = (deleteNivelDefinicaoResponseSuccess)

export const getDeleteNivelDefinicaoUrl = (id: number,) => {


  

  return `http://localhost:3333/api/v1/nivel-definicao/${id}`
}

export const deleteNivelDefinicao = async (id: number, options?: RequestInit): Promise<deleteNivelDefinicaoResponse> => {
  
  const res = await fetch(getDeleteNivelDefinicaoUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteNivelDefinicaoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteNivelDefinicaoResponse
}



export type getByIdNivelDefinicaoResponse200 = {
  data: NivelDefinicao
  status: 200
}
    
export type getByIdNivelDefinicaoResponseSuccess = (getByIdNivelDefinicaoResponse200) & {
  headers: Headers;
};
;

export type getByIdNivelDefinicaoResponse = (getByIdNivelDefinicaoResponseSuccess)

export const getGetByIdNivelDefinicaoUrl = (id: number,) => {


  

  return `http://localhost:3333/api/v1/nivel-definicao/${id}`
}

export const getByIdNivelDefinicao = async (id: number, options?: RequestInit): Promise<getByIdNivelDefinicaoResponse> => {
  
  const res = await fetch(getGetByIdNivelDefinicaoUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getByIdNivelDefinicaoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getByIdNivelDefinicaoResponse
}



export type updateNivelDefinicaoResponse200 = {
  data: NivelDefinicao
  status: 200
}
    
export type updateNivelDefinicaoResponseSuccess = (updateNivelDefinicaoResponse200) & {
  headers: Headers;
};
;

export type updateNivelDefinicaoResponse = (updateNivelDefinicaoResponseSuccess)

export const getUpdateNivelDefinicaoUrl = (id: number,) => {


  

  return `http://localhost:3333/api/v1/nivel-definicao/${id}`
}

export const updateNivelDefinicao = async (id: number,
    nivelDefinicaoDto: NivelDefinicaoDto, options?: RequestInit): Promise<updateNivelDefinicaoResponse> => {
  
  const res = await fetch(getUpdateNivelDefinicaoUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      nivelDefinicaoDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updateNivelDefinicaoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateNivelDefinicaoResponse
}



export type createQuestionarioResponse200 = {
  data: Questionario
  status: 200
}
    
export type createQuestionarioResponseSuccess = (createQuestionarioResponse200) & {
  headers: Headers;
};
;

export type createQuestionarioResponse = (createQuestionarioResponseSuccess)

export const getCreateQuestionarioUrl = () => {


  

  return `http://localhost:3333/api/v1/questionario`
}

export const createQuestionario = async (questionario: Questionario, options?: RequestInit): Promise<createQuestionarioResponse> => {
  
  const res = await fetch(getCreateQuestionarioUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      questionario,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createQuestionarioResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createQuestionarioResponse
}



export type getAllQuestionariosResponse200 = {
  data: GetAllQuestionarios200
  status: 200
}
    
export type getAllQuestionariosResponseSuccess = (getAllQuestionariosResponse200) & {
  headers: Headers;
};
;

export type getAllQuestionariosResponse = (getAllQuestionariosResponseSuccess)

export const getGetAllQuestionariosUrl = () => {


  

  return `http://localhost:3333/api/v1/questionario/all`
}

export const getAllQuestionarios = async ( options?: RequestInit): Promise<getAllQuestionariosResponse> => {
  
  const res = await fetch(getGetAllQuestionariosUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getAllQuestionariosResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAllQuestionariosResponse
}



export type getQuestionarioByMissaoResponse200 = {
  data: Questionario
  status: 200
}
    
export type getQuestionarioByMissaoResponseSuccess = (getQuestionarioByMissaoResponse200) & {
  headers: Headers;
};
;

export type getQuestionarioByMissaoResponse = (getQuestionarioByMissaoResponseSuccess)

export const getGetQuestionarioByMissaoUrl = (missaoId: number,) => {


  

  return `http://localhost:3333/api/v1/questionario/missao/${missaoId}`
}

export const getQuestionarioByMissao = async (missaoId: number, options?: RequestInit): Promise<getQuestionarioByMissaoResponse> => {
  
  const res = await fetch(getGetQuestionarioByMissaoUrl(missaoId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getQuestionarioByMissaoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getQuestionarioByMissaoResponse
}



export type deleteQuestionarioResponse200 = {
  data: string
  status: 200
}
    
export type deleteQuestionarioResponseSuccess = (deleteQuestionarioResponse200) & {
  headers: Headers;
};
;

export type deleteQuestionarioResponse = (deleteQuestionarioResponseSuccess)

export const getDeleteQuestionarioUrl = (id: number,) => {


  

  return `http://localhost:3333/api/v1/questionario/${id}`
}

export const deleteQuestionario = async (id: number, options?: RequestInit): Promise<deleteQuestionarioResponse> => {
  
  const res = await fetch(getDeleteQuestionarioUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteQuestionarioResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteQuestionarioResponse
}



export type getByIdQuestionarioResponse200 = {
  data: Questionario
  status: 200
}
    
export type getByIdQuestionarioResponseSuccess = (getByIdQuestionarioResponse200) & {
  headers: Headers;
};
;

export type getByIdQuestionarioResponse = (getByIdQuestionarioResponseSuccess)

export const getGetByIdQuestionarioUrl = (id: number,) => {


  

  return `http://localhost:3333/api/v1/questionario/${id}`
}

export const getByIdQuestionario = async (id: number, options?: RequestInit): Promise<getByIdQuestionarioResponse> => {
  
  const res = await fetch(getGetByIdQuestionarioUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getByIdQuestionarioResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getByIdQuestionarioResponse
}



export type updateQuestionarioResponse200 = {
  data: Questionario
  status: 200
}
    
export type updateQuestionarioResponseSuccess = (updateQuestionarioResponse200) & {
  headers: Headers;
};
;

export type updateQuestionarioResponse = (updateQuestionarioResponseSuccess)

export const getUpdateQuestionarioUrl = (id: number,) => {


  

  return `http://localhost:3333/api/v1/questionario/${id}`
}

export const updateQuestionario = async (id: number,
    questionario: Questionario, options?: RequestInit): Promise<updateQuestionarioResponse> => {
  
  const res = await fetch(getUpdateQuestionarioUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      questionario,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updateQuestionarioResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateQuestionarioResponse
}



export type createTurmaResponse200 = {
  data: Turma
  status: 200
}
    
export type createTurmaResponseSuccess = (createTurmaResponse200) & {
  headers: Headers;
};
;

export type createTurmaResponse = (createTurmaResponseSuccess)

export const getCreateTurmaUrl = () => {


  

  return `http://localhost:3333/api/v1/turma`
}

export const createTurma = async (turmaDto: TurmaDto, options?: RequestInit): Promise<createTurmaResponse> => {
  
  const res = await fetch(getCreateTurmaUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      turmaDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createTurmaResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createTurmaResponse
}



export type getAllTurmaResponse200 = {
  data: Turma[]
  status: 200
}
    
export type getAllTurmaResponseSuccess = (getAllTurmaResponse200) & {
  headers: Headers;
};
;

export type getAllTurmaResponse = (getAllTurmaResponseSuccess)

export const getGetAllTurmaUrl = () => {


  

  return `http://localhost:3333/api/v1/turma/all`
}

export const getAllTurma = async ( options?: RequestInit): Promise<getAllTurmaResponse> => {
  
  const res = await fetch(getGetAllTurmaUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getAllTurmaResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAllTurmaResponse
}



export type getTurmasResponse200 = {
  data: number
  status: 200
}
    
export type getTurmasResponseSuccess = (getTurmasResponse200) & {
  headers: Headers;
};
;

export type getTurmasResponse = (getTurmasResponseSuccess)

export const getGetTurmasUrl = () => {


  

  return `http://localhost:3333/api/v1/turma/qt`
}

export const getTurmas = async ( options?: RequestInit): Promise<getTurmasResponse> => {
  
  const res = await fetch(getGetTurmasUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getTurmasResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getTurmasResponse
}



export type deleteTurmaResponse200 = {
  data: string
  status: 200
}
    
export type deleteTurmaResponseSuccess = (deleteTurmaResponse200) & {
  headers: Headers;
};
;

export type deleteTurmaResponse = (deleteTurmaResponseSuccess)

export const getDeleteTurmaUrl = (id: number,) => {


  

  return `http://localhost:3333/api/v1/turma/${id}`
}

export const deleteTurma = async (id: number, options?: RequestInit): Promise<deleteTurmaResponse> => {
  
  const res = await fetch(getDeleteTurmaUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteTurmaResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteTurmaResponse
}



export type updateTurmaResponse200 = {
  data: Turma
  status: 200
}
    
export type updateTurmaResponseSuccess = (updateTurmaResponse200) & {
  headers: Headers;
};
;

export type updateTurmaResponse = (updateTurmaResponseSuccess)

export const getUpdateTurmaUrl = (id: number,) => {


  

  return `http://localhost:3333/api/v1/turma/${id}`
}

export const updateTurma = async (id: number,
    turmaDto: TurmaDto, options?: RequestInit): Promise<updateTurmaResponse> => {
  
  const res = await fetch(getUpdateTurmaUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      turmaDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updateTurmaResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateTurmaResponse
}



export type getUserByIdResponse200 = {
  data: User
  status: 200
}
    
export type getUserByIdResponseSuccess = (getUserByIdResponse200) & {
  headers: Headers;
};
;

export type getUserByIdResponse = (getUserByIdResponseSuccess)

export const getGetUserByIdUrl = (params: GetUserByIdParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:3333/api/v1/user?${stringifiedParams}` : `http://localhost:3333/api/v1/user`
}

export const getUserById = async (params: GetUserByIdParams, options?: RequestInit): Promise<getUserByIdResponse> => {
  
  const res = await fetch(getGetUserByIdUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getUserByIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getUserByIdResponse
}



export type createUserResponse200 = {
  data: User
  status: 200
}
    
export type createUserResponseSuccess = (createUserResponse200) & {
  headers: Headers;
};
;

export type createUserResponse = (createUserResponseSuccess)

export const getCreateUserUrl = () => {


  

  return `http://localhost:3333/api/v1/user`
}

export const createUser = async (userDto: UserDto, options?: RequestInit): Promise<createUserResponse> => {
  
  const res = await fetch(getCreateUserUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      userDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createUserResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createUserResponse
}



export type getUserResponse200 = {
  data: User[]
  status: 200
}
    
export type getUserResponseSuccess = (getUserResponse200) & {
  headers: Headers;
};
;

export type getUserResponse = (getUserResponseSuccess)

export const getGetUserUrl = () => {


  

  return `http://localhost:3333/api/v1/user/all`
}

export const getUser = async ( options?: RequestInit): Promise<getUserResponse> => {
  
  const res = await fetch(getGetUserUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getUserResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getUserResponse
}



export type getQtUsersResponse200 = {
  data: number
  status: 200
}
    
export type getQtUsersResponseSuccess = (getQtUsersResponse200) & {
  headers: Headers;
};
;

export type getQtUsersResponse = (getQtUsersResponseSuccess)

export const getGetQtUsersUrl = () => {


  

  return `http://localhost:3333/api/v1/user/qt`
}

export const getQtUsers = async ( options?: RequestInit): Promise<getQtUsersResponse> => {
  
  const res = await fetch(getGetQtUsersUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getQtUsersResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getQtUsersResponse
}
